### PR TITLE
Add starter file for required JavaScript

### PR DESCRIPTION
**Pull request by natec425**
The provided file leads the student a bit more on how they should
structure their solution. It includes a DOMContentLoaded listener
that should call solution functions.

Also, a solution to the first problem is provided to additional
guidance on what a solution might look like.

### CODE REVIEW

**Review by john-terenzio — APPROVED** [review]
LGTM

Question: We could hold off on the idea of a listener for DOM loaded and just put scripts at the bottom of the HTML so that the solution is just the last 4 lines. Thoughts? We could then introduce that event along with other events.

**Comment by natec425** [comment]
That sounds good to me.

What do you think about the pieces of this assignment that require adding an event listener (like the alert button). Move those to a new assignment all about events and replace them with event-less work here?

**Comment by john-terenzio** [comment]
I think separating target practice and events (with a self-contained lesson about events) would be my instinct.

**Comment by natec425** [comment]
I think I broke this PR by locally rebasing it into master. I'll try to not do that in the future...

**Pull request closed without merging**
